ignore:
  - "**/*Module.java"
  - "**/LogoutTexts.java"
  - "**/RejectReasons.java"
  - "**/FixFieldsTypes.java"
  - "**/*Exception.java"
  - "**/FakeFixSpec.java"
  - "**/StandardHeaderAndFooterOnlyFixSpec.java"